package com.yanagikh.keepg.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import com.yanagikh.keepg.data.AppLanguage
import java.util.Locale

internal val LocalAppLanguage = compositionLocalOf { AppLanguage.AUTO }

@Composable
internal fun tr(key: String): String = UiLocalizer.text(LocalAppLanguage.current, key)

@Composable
internal fun trf(key: String, vararg args: Any): String = String.format(Locale.ROOT, tr(key), *args)

internal object UiLocalizer {
    fun text(language: AppLanguage, key: String): String {
        val code = when (language) {
            AppLanguage.AUTO -> when (Locale.getDefault().language.lowercase(Locale.ROOT)) {
                "zh" -> "zh"
                "ja" -> "ja"
                "ko" -> "ko"
                else -> "en"
            }
            AppLanguage.ENGLISH -> "en"
            AppLanguage.CHINESE -> "zh"
            AppLanguage.JAPANESE -> "ja"
            AppLanguage.KOREAN -> "ko"
        }
        return dictionaries[code]?.get(key) ?: key
    }

    private val dictionaries = mapOf(
        "zh" to mapOf(
            "Photos" to "相片",
            "Albums" to "相簿",
            "Smart" to "智慧",
            "Vault" to "保險庫",
            "Settings" to "設定",
            "Refresh" to "重新整理",
            "Search media and albums" to "搜尋媒體與相簿",
            "Filters" to "篩選",
            "Sort" to "排序",
            "All" to "全部",
            "Images" to "圖片",
            "Videos" to "影片",
            "GIFs" to "GIF",
            "Any size" to "任何大小",
            "Small < 1 MB" to "小於 1 MB",
            "Medium 1–10 MB" to "1–10 MB",
            "Large > 10 MB" to "大於 10 MB",
            "Date" to "日期",
            "Name" to "名稱",
            "Size" to "大小",
            "Extension" to "副檔名",
            "Descending" to "遞減",
            "Ascending" to "遞增",
            "Favorites" to "我的最愛",
            "No media yet" to "尚無媒體",
            "Grant photo and video access, then refresh your library." to "授予相片與影片存取權後重新整理媒體庫。",
            "Protected" to "已保護",
            "Back" to "返回",
            "Collections" to "收藏集",
            "New collection" to "新增收藏集",
            "Device albums" to "裝置相簿",
            "Create" to "建立",
            "Cancel" to "取消",
            "Close" to "關閉",
            "Preview" to "預覽",
            "Favorite" to "加入最愛",
            "Unfavorite" to "移除最愛",
            "Share" to "分享",
            "Edit" to "編輯",
            "Delete" to "刪除",
            "Details" to "詳細資訊",
            "Protect" to "上鎖",
            "Unlock" to "解鎖",
            "Repair" to "修復",
            "Analyze" to "分析",
            "Links" to "連結",
            "Collection" to "收藏集",
            "Selected: %s" to "已選取：%s",
            "Clear selection" to "清除選取",
            "Share selected" to "分享已選項目",
            "Delete selected" to "刪除已選項目",
            "Favorite selected" to "將已選項目加入最愛",
            "Video preview autoplay" to "相簿影片預覽自動播放",
            "Play muted looping video previews in the media grid." to "在媒體格狀清單中靜音循環播放影片預覽。",
            "Delete to recoverable trash" to "刪除時移到可復原垃圾桶",
            "Use Android MediaStore trash when available instead of immediate permanent deletion." to "可用時使用 Android MediaStore 垃圾桶，而非立即永久刪除。",
            "Hide likely NSFW / graphic content" to "隱藏疑似 NSFW／血腥內容",
            "Uses an on-device visual heuristic. It can make mistakes; hidden media is never deleted." to "使用裝置端視覺演算法，可能誤判；隱藏媒體不會被刪除。",
            "Language" to "語言",
            "Automatic" to "自動",
            "English" to "英文",
            "Chinese" to "中文",
            "Japanese" to "日文",
            "Korean" to "韓文",
            "Deletion password" to "刪除密碼",
            "Set or replace the password required before deleting media." to "設定或更換刪除媒體前必須輸入的密碼。",
            "Set password" to "設定密碼",
            "Password" to "密碼",
            "Save" to "儲存",
            "Media permissions" to "媒體權限",
            "Grant" to "授予",
            "Debug logging" to "除錯日誌",
            "Export log" to "匯出日誌",
            "View log" to "查看日誌",
            "Clear" to "清除",
            "Image editor" to "圖片編輯器",
            "Video editor" to "影片編輯器",
            "Drag with one finger; pinch with two fingers to move and scale." to "單指拖移，雙指縮放以移動與調整大小。",
            "Output name" to "輸出名稱",
            "Crop" to "裁切",
            "Original" to "原始",
            "Square" to "正方形",
            "4:3" to "4:3",
            "16:9" to "16:9",
            "Background" to "背景",
            "Keep background" to "保留背景",
            "Auto remove" to "自動去背",
            "Manual remove" to "手動去背",
            "Layers" to "圖層",
            "Add text layer" to "新增文字圖層",
            "Text layer" to "文字圖層",
            "Apply edit" to "套用編輯",
            "Trim first 5 seconds" to "保留前 5 秒",
            "Create muted copy" to "建立靜音副本",
            "Playback speed" to "播放速度",
            "Quality" to "畫質",
            "Auto quality" to "自動畫質",
            "Original quality" to "原始畫質",
            "Long-press a URL or QR code in the image to open it." to "在圖片中的 URL 或 QR Code 上長按即可提取連結。",
            "Links found" to "找到連結",
            "No web links or QR URLs found" to "未找到網頁連結或 QR URL",
            "Share media" to "分享媒體",
            "Optional password" to "選用密碼",
            "Leave blank for normal sharing. A password creates an AES-encrypted ZIP." to "留空為一般分享；輸入密碼會建立 AES 加密 ZIP。",
            "Delete media" to "刪除媒體",
            "Create deletion password" to "建立刪除密碼",
            "Enter deletion password" to "輸入刪除密碼",
            "Move to trash" to "移到垃圾桶",
            "Delete permanently" to "永久刪除",
            "Incorrect password" to "密碼錯誤",
            "Use at least 6 characters" to "請使用至少 6 個字元",
            "File information" to "檔案資訊",
            "Duration" to "長度",
            "Resolution" to "解析度",
            "MIME type" to "MIME 類型",
            "Album" to "相簿",
            "Modified" to "日期",
            "File size" to "檔案大小",
            "Rename" to "重新命名",
            "Rename media" to "重新命名媒體",
            "On-device smart organization" to "裝置端智慧整理",
            "Analyze library" to "分析媒體庫",
            "Analyzing…" to "分析中…",
            "People" to "人物",
            "Smart albums" to "智慧相簿",
            "Rule" to "規則",
            "Name person group" to "命名人物群組",
            "Create smart album rule" to "建立智慧相簿規則"
        ),
        "ja" to mapOf(
            "Photos" to "写真",
            "Albums" to "アルバム",
            "Smart" to "スマート",
            "Vault" to "保管庫",
            "Settings" to "設定",
            "Refresh" to "更新",
            "Search media and albums" to "メディアとアルバムを検索",
            "Filters" to "フィルター",
            "Sort" to "並べ替え",
            "All" to "すべて",
            "Images" to "画像",
            "Videos" to "動画",
            "GIFs" to "GIF",
            "Date" to "日付",
            "Name" to "名前",
            "Size" to "サイズ",
            "Extension" to "拡張子",
            "Favorites" to "お気に入り",
            "No media yet" to "メディアがありません",
            "Protected" to "保護済み",
            "Back" to "戻る",
            "Collections" to "コレクション",
            "New collection" to "新しいコレクション",
            "Device albums" to "端末アルバム",
            "Create" to "作成",
            "Cancel" to "キャンセル",
            "Close" to "閉じる",
            "Favorite" to "お気に入り",
            "Unfavorite" to "お気に入り解除",
            "Share" to "共有",
            "Edit" to "編集",
            "Delete" to "削除",
            "Details" to "詳細",
            "Protect" to "ロック",
            "Unlock" to "ロック解除",
            "Repair" to "修復",
            "Analyze" to "分析",
            "Links" to "リンク",
            "Video preview autoplay" to "動画プレビューを自動再生",
            "Delete to recoverable trash" to "削除時に復元可能なゴミ箱へ移動",
            "Hide likely NSFW / graphic content" to "NSFW・刺激の強い内容を非表示",
            "Language" to "言語",
            "Automatic" to "自動",
            "English" to "英語",
            "Chinese" to "中国語",
            "Japanese" to "日本語",
            "Korean" to "韓国語",
            "Deletion password" to "削除パスワード",
            "Set password" to "パスワード設定",
            "Password" to "パスワード",
            "Save" to "保存",
            "Media permissions" to "メディア権限",
            "Grant" to "許可",
            "Debug logging" to "デバッグログ",
            "Export log" to "ログを書き出す",
            "View log" to "ログを見る",
            "Clear" to "消去",
            "Image editor" to "画像エディター",
            "Video editor" to "動画エディター",
            "Output name" to "出力名",
            "Crop" to "切り抜き",
            "Original" to "元の比率",
            "Square" to "正方形",
            "Background" to "背景",
            "Keep background" to "背景を保持",
            "Auto remove" to "自動削除",
            "Manual remove" to "手動削除",
            "Layers" to "レイヤー",
            "Add text layer" to "テキストレイヤーを追加",
            "Apply edit" to "編集を適用",
            "Playback speed" to "再生速度",
            "Quality" to "画質",
            "Auto quality" to "自動画質",
            "Original quality" to "元の画質",
            "Links found" to "リンクを検出",
            "Share media" to "メディアを共有",
            "Optional password" to "任意のパスワード",
            "Delete media" to "メディアを削除",
            "Create deletion password" to "削除パスワードを作成",
            "Enter deletion password" to "削除パスワードを入力",
            "Move to trash" to "ゴミ箱へ移動",
            "Delete permanently" to "完全に削除",
            "Incorrect password" to "パスワードが違います",
            "Use at least 6 characters" to "6文字以上を使用してください",
            "File information" to "ファイル情報",
            "Duration" to "長さ",
            "Resolution" to "解像度",
            "MIME type" to "MIMEタイプ",
            "Album" to "アルバム",
            "Modified" to "日付",
            "File size" to "ファイルサイズ",
            "Rename" to "名前変更",
            "On-device smart organization" to "端末上のスマート整理",
            "Analyze library" to "ライブラリを分析",
            "Analyzing…" to "分析中…",
            "People" to "人物",
            "Smart albums" to "スマートアルバム",
            "Rule" to "ルール"
        ),
        "ko" to mapOf(
            "Photos" to "사진",
            "Albums" to "앨범",
            "Smart" to "스마트",
            "Vault" to "보관함",
            "Settings" to "설정",
            "Refresh" to "새로고침",
            "Search media and albums" to "미디어 및 앨범 검색",
            "Filters" to "필터",
            "Sort" to "정렬",
            "All" to "전체",
            "Images" to "이미지",
            "Videos" to "동영상",
            "GIFs" to "GIF",
            "Date" to "날짜",
            "Name" to "이름",
            "Size" to "크기",
            "Extension" to "확장자",
            "Favorites" to "즐겨찾기",
            "No media yet" to "미디어가 없습니다",
            "Protected" to "보호됨",
            "Back" to "뒤로",
            "Collections" to "컬렉션",
            "New collection" to "새 컬렉션",
            "Device albums" to "기기 앨범",
            "Create" to "만들기",
            "Cancel" to "취소",
            "Close" to "닫기",
            "Favorite" to "즐겨찾기",
            "Unfavorite" to "즐겨찾기 해제",
            "Share" to "공유",
            "Edit" to "편집",
            "Delete" to "삭제",
            "Details" to "세부 정보",
            "Protect" to "잠금",
            "Unlock" to "잠금 해제",
            "Repair" to "복구",
            "Analyze" to "분석",
            "Links" to "링크",
            "Video preview autoplay" to "동영상 미리보기 자동 재생",
            "Delete to recoverable trash" to "삭제 시 복구 가능한 휴지통으로 이동",
            "Hide likely NSFW / graphic content" to "NSFW/선정적 콘텐츠 숨기기",
            "Language" to "언어",
            "Automatic" to "자동",
            "English" to "영어",
            "Chinese" to "중국어",
            "Japanese" to "일본어",
            "Korean" to "한국어",
            "Deletion password" to "삭제 비밀번호",
            "Set password" to "비밀번호 설정",
            "Password" to "비밀번호",
            "Save" to "저장",
            "Media permissions" to "미디어 권한",
            "Grant" to "허용",
            "Debug logging" to "디버그 로그",
            "Export log" to "로그 내보내기",
            "View log" to "로그 보기",
            "Clear" to "지우기",
            "Image editor" to "이미지 편집기",
            "Video editor" to "동영상 편집기",
            "Output name" to "출력 이름",
            "Crop" to "자르기",
            "Original" to "원본",
            "Square" to "정사각형",
            "Background" to "배경",
            "Keep background" to "배경 유지",
            "Auto remove" to "자동 제거",
            "Manual remove" to "수동 제거",
            "Layers" to "레이어",
            "Add text layer" to "텍스트 레이어 추가",
            "Apply edit" to "편집 적용",
            "Playback speed" to "재생 속도",
            "Quality" to "화질",
            "Auto quality" to "자동 화질",
            "Original quality" to "원본 화질",
            "Links found" to "링크 발견",
            "Share media" to "미디어 공유",
            "Optional password" to "선택 비밀번호",
            "Delete media" to "미디어 삭제",
            "Create deletion password" to "삭제 비밀번호 만들기",
            "Enter deletion password" to "삭제 비밀번호 입력",
            "Move to trash" to "휴지통으로 이동",
            "Delete permanently" to "영구 삭제",
            "Incorrect password" to "비밀번호가 올바르지 않습니다",
            "Use at least 6 characters" to "6자 이상 사용하세요",
            "File information" to "파일 정보",
            "Duration" to "길이",
            "Resolution" to "해상도",
            "MIME type" to "MIME 유형",
            "Album" to "앨범",
            "Modified" to "날짜",
            "File size" to "파일 크기",
            "Rename" to "이름 바꾸기",
            "On-device smart organization" to "기기 내 스마트 정리",
            "Analyze library" to "라이브러리 분석",
            "Analyzing…" to "분석 중…",
            "People" to "인물",
            "Smart albums" to "스마트 앨범",
            "Rule" to "규칙"
        )
    )
}
